export const defaultGroups = [
  {
    id: "nyugati_megyek",
    label: "Nyugati megyék",
    districts: [
      { megyekod: 20, oevk: 1 },
      { megyekod: 20, oevk: 2 },
      { megyekod: 20, oevk: 3 },
      { megyekod: 18, oevk: 1 },
      { megyekod: 18, oevk: 2 },
      { megyekod: 18, oevk: 3 },
      { megyekod: 8, oevk: 1 },
      { megyekod: 8, oevk: 2 },
      { megyekod: 8, oevk: 3 },
      { megyekod: 8, oevk: 4 },
      { megyekod: 8, oevk: 5 },
    ],
  },
  {
    id: "keleti_megyek",
    label: "Keleti megyék",
    districts: [
      { megyekod: 9, oevk: 1 },
      { megyekod: 9, oevk: 2 },
      { megyekod: 9, oevk: 3 },
      { megyekod: 9, oevk: 4 },
      { megyekod: 9, oevk: 5 },
      { megyekod: 9, oevk: 6 },
      { megyekod: 16, oevk: 1 },
      { megyekod: 16, oevk: 2 },
      { megyekod: 16, oevk: 3 },
      { megyekod: 16, oevk: 4 },
      { megyekod: 16, oevk: 5 },
      { megyekod: 16, oevk: 6 },
      { megyekod: 4, oevk: 1 },
      { megyekod: 4, oevk: 2 },
      { megyekod: 4, oevk: 3 },
      { megyekod: 4, oevk: 4 },
    ],
  },
];
