export const quotes = [
  "„A demokrácia nem megoldás, hanem probléma, amelyet minden nap újra kell kezelni.” — Tamás Gáspár Miklós",
  "„A választás nem erkölcsi feloldozás, hanem technikai döntés következményekkel.” — Tamás Gáspár Miklós",
  "„A politika nem az igazság keresése, hanem a hatalom gyakorlása.” — Tamás Gáspár Miklós",
  "„A szabadság nem attól sérül, hogy elveszik, hanem attól, hogy megszokjuk a hiányát.” — Tamás Gáspár Miklós",
  "„A hatalom mindig túl sokat akar, ha nem szólnak rá.” — Konrád György",
  "„A demokrácia nem a csendes egyetértés, hanem a hangos vita rendszere.” — Konrád György",
  "„A politikai lojalitás gyorsabban rombol, mint a nyílt ellenségesség.” — Konrád György",
  "„Demokratának lenni mindenekelőtt annyit jelent, mint nem félni.” — Bibó István",
  "„A hatalom önigazolása mindig gyanús.” — Bibó István",
  "„Tetszettek volna forradalmat csinálni.” — Antall József",
  "Mi nem ígértünk könnyű jövőt, csak tisztességeset. — Antall József",
  "Ez a kormány nem népszerűségi versenyre szerződött. — Antall József",
  "A demokrácia nem a nyugalom állapota, hanem az állandó vita terepe. — Antall József",
  "Aki kormányoz, annak dönteni kell, akkor is, ha nem tapsolnak. — Antall József",
  "A politika nem az erkölcsi tisztaság versenye, hanem a lehetőségeké. — Horn Gyula",
  "Nem azért nyertük meg a választást, hogy ne csináljunk semmit. — Horn Gyula",
  "A kompromisszum nem árulás, hanem módszer. — Horn Gyula",
  "A választók nem szeretik, ha hülyének nézik őket. — Horn Gyula",
  "A politikában vannak pillanatok, amikor nem lehet félrenézni. — Orbán Viktor",
  "A választás nem véleménykutatás, hanem döntés. — Orbán Viktor",
  "Aki elveszíti a választást, annak tudnia kell veszíteni. — Orbán Viktor",
  "A politikában nem az számít, hogy mit gondolunk magunkról, hanem hogy mit gondolnak rólunk. — Orbán Viktor",
  "A hatalom nem önigazolás, hanem felelősség. — Orbán Viktor",
  "Azt hittük, elég ügyesnek lenni, és nem kell őszintének. — Gyurcsány Ferenc",
  "Ezt nem lehet tovább úgy csinálni, mintha minden rendben lenne. — Gyurcsány Ferenc",
  "A politikában a kudarc nem mentség, hanem állapot. — Gyurcsány Ferenc",
  "Megnyertük a választást, de elveszítettük a hitelességet. — Gyurcsány Ferenc",
  "A demokrácia nem attól működik, hogy szeretjük egymást. — Göncz Árpád",
  "A köztársaság nem a győztesek jutalma. — Göncz Árpád",
  "A hatalom önmagában nem teremt igazságot. — Göncz Árpád",
  "A jogállam nem akkor fontos, amikor egyetértünk vele. — Sólyom László",
  "A többség nem jogosult mindent megtenni. — Sólyom László",
  "A demokrácia nem gyors, de kiszámítható kell hogy legyen. — Sólyom László",
  "Nem finomkodni jöttünk ide, hanem rendet tenni. — Torgyán József",
  "Aki fél a konfliktustól, ne menjen politikusnak. — Torgyán József",
  "Az emberek nem ideológiát akarnak, hanem biztonságot. — Medgyessy Péter",
  "A választási ígéret nem költői műfaj. — Medgyessy Péter",
  "Nem népszerű döntések nélkül nincs kormányzás. — Bajnai Gordon",
  "A válság nem kampányhelyzet. — Bajnai Gordon",
  "A politika nem udvariassági sport. — Kövér László",
  "Aki uralmat akar, az fél a vitától. — Kövér László",
  "A demokrácia nem megoldás, hanem probléma, amit kezelni kell. — Tamás Gáspár Miklós",
  "A választás nem erkölcsi feloldozás. — Tamás Gáspár Miklós",
  "A rendszer nem attól demokratikus, hogy választás van. — Schiffer András",
];
